### ISSUE TITLE
Authentication/Credentials Backend

### ISSUE THREAD

**Issue by VaVoose** [VaVoose/traak-cmms#10]

**Comment by Rektroth** [comment]
As it stands right now, the authentication by itself is working, however sessions are active until the API restarts. I need to have the session authenticator store session data in postgres and make a query for the user's session every time they load the site.

**Comment by Rektroth** [comment]
I would say that this issue can be closed when #49 is closed.

**Comment by VaVoose** [comment]
There is an issue of the user being soft locked out of the application. There needs to be an API call for a user to be logged out in the backend. Steps to reproduce:
1. Login with email and pass
2. Click the logout button
3. Try to log in (doesn't work - 400 already logged in)

Expected results -> User should be able to log in on a different account

**Comment by Rektroth** [comment]
Finishing this is going to require a session store.
https://www.npmjs.com/package/connect-pg-simple

**Comment by Rektroth** [comment]
Last thing to do for this is to invalidate user sessions when their account is deleted.
