### ISSUE TITLE
Missing API calls

### ISSUE THREAD

**Issue by VaVoose** [VaVoose/traak-cmms#27]
This is where we will all put any API calls that the frontend people need to fill certain tables information in the frontend that are not currently available.

**Comment by VaVoose** [comment]
Vendor information needs to be added to the schema and be able to be pulled from API. The current information associated with a vendor are [Vendor Name, Location (address), a main contact, a list of all available contacts, a list of associated parts, and a list of associated equipment].

**Comment by Rektroth** [comment]
Should contacts be people or just addresses/numbers? And should vendors be associated with the equipment or the manufacturers?

**Comment by VaVoose** [comment]
A contact should be a Name and a phone number for now. The second part is a good question. We ask Wayne

**Comment by Rektroth** [comment]
Campuses and zones are implemented.
