### ISSUE TITLE
There is currently no way to edit or add equipment

### ISSUE THREAD

**Issue by VaVoose** [VaVoose/traak-cmms#28]
The user should be able to edit and add equipment if they need too. There is currently no such way of doing that

**Comment by VaVoose** [comment]
Basic modal is in place

**Comment by Rektroth** [comment]
New equipment must be able to be associated to inventory items when created.

**Comment by Rektroth** [comment]
Oooh, doing that is gonna require the transactions feature.

**Comment by Rektroth** [comment]
Latest commit also added the ability to associate inventory with a new piece of equipment.
Error data is also now much more helpful, as the API will not vet data before attempting to insert into the database.

**Comment by Rektroth** [comment]
There is now a deletion feature, but a boolean property should be added to equipment specifying whether or not the equipment is "in use" in order to discourage use of this feature.

**Comment by Rektroth** [comment]
This issue is now technically closed, but I will create a new ticket specifying that similar functionality must be added for other database objects.
